### ISSUE TITLE
Just to say thanks

### ISSUE THREAD

**Issue by DKingAlpha** [Skyfail/CSkyDBK#1]
Found this Before I read thro IOPLDispatcher.cpp After creating project DBK_Caller.

This saved my time. Thanks.

**Comment by DKingAlpha** [comment]
btw, I got a [DBKKernel](https://github.com/DKingCN/DBKKernel) here supporting win10x64

**Comment by Skyfail** [comment]
I’m happy that my project helped you.
The shipped and signed Version of DBK does seem to work on the latest win10 x64 build for me tho
